### ISSUE TITLE
ftp://ftp.rsa.com/pub/pkcs/ascii/layman.asc not accessible anymore ?

### ISSUE THREAD

**Issue by jlguenego** [joyent/node-asn1#45]
The README mentions ftp://ftp.rsa.com/pub/pkcs/ascii/layman.asc
The link seems to be broken.
Please could you indicate another link ?
Thanks.

**Comment by rprimus** [comment]
Sat 5 Mar 2022 10:20:22 GMT

Hi @jlguenego (and anyone else looking for this): 

The full document name is `A Layman's Guide to a Subset of ASN.1, BER, and DER`.
 It is (currently) available at https://opensource.apple.com/source/Heimdal/Heimdal-520/doc/layman.asc.auto.html.
